function erps = LEAP_EEG_faces_findPeaks(erps, peakN1, peakP1, winWidth)

    % search windows
    if ~exist('peakN1', 'var') || isempty(peakN1)
        peakN1 = 0.228;
    end
    
    if ~exist('peakP1', 'var') || isempty(peakP1)
        peakP1 = 0.166;
    end
    
    if ~exist('winWidth', 'var') || isempty(winWidth)
        winWidth = 0.030;
    end
    
    windowsN1 = repmat([peakN1 - winWidth; peakN1 + winWidth], 1, 3);
    windowsP1 = repmat([peakP1 - winWidth; peakP1 + winWidth], 1, 3);

    % find - P1 | upright
    [pks_fu_p1_p7, locs_fu_p1_p7] = eegFindPeak(erps.face_up,...
        windowsP1(:, 1)', 'P7', 250, 'positive');
    [pks_fu_p1_pz, locs_fu_p1_pz] = eegFindPeak(erps.face_up,...
        windowsP1(:, 2)', 'Pz', 250, 'positive');        
    [pks_fu_p1_p8, locs_fu_p1_p8] = eegFindPeak(erps.face_up,...
        windowsP1(:, 3)', 'P8', 250, 'positive');   
    [pks_fu_p1_o1, locs_fu_p1_o1] = eegFindPeak(erps.face_up,...
        windowsP1(:, 1)', 'O1', 250, 'positive');
    [pks_fu_p1_oz, locs_fu_p1_oz] = eegFindPeak(erps.face_up,...
        windowsP1(:, 2)', 'Oz', 250, 'positive');        
    [pks_fu_p1_o2, locs_fu_p1_o2] = eegFindPeak(erps.face_up,...
        windowsP1(:, 3)', 'O2', 250, 'positive');    
    
    % store - P1 | upright
    erps.face_up = eegStorePeak(erps.face_up, 'P1', 'P7',...
        pks_fu_p1_p7, locs_fu_p1_p7);
    erps.face_up = eegStorePeak(erps.face_up, 'P1', 'Pz',...
        pks_fu_p1_pz, locs_fu_p1_pz);
    erps.face_up = eegStorePeak(erps.face_up, 'P1', 'P8',...
        pks_fu_p1_p8, locs_fu_p1_p8);
    erps.face_up = eegStorePeak(erps.face_up, 'P1', 'O1',...
        pks_fu_p1_o1, locs_fu_p1_o1);
    erps.face_up = eegStorePeak(erps.face_up, 'P1', 'Oz',...
        pks_fu_p1_oz, locs_fu_p1_oz);
    erps.face_up = eegStorePeak(erps.face_up, 'P1', 'O2',...
        pks_fu_p1_o2, locs_fu_p1_o2);
    
    % find - P1 | inverted
    [pks_fi_p1_p7, locs_fi_p1_p7] = eegFindPeak(erps.face_inv,...
        windowsP1(:, 1)', 'P7', 250, 'positive');
    [pks_fi_p1_pz, locs_fi_p1_pz] = eegFindPeak(erps.face_inv,...
        windowsP1(:, 2)', 'Pz', 250, 'positive');        
    [pks_fi_p1_p8, locs_fi_p1_p8] = eegFindPeak(erps.face_inv,...
        windowsP1(:, 3)', 'P8', 250, 'positive');   
    [pks_fi_p1_o1, locs_fi_p1_o1] = eegFindPeak(erps.face_inv,...
        windowsP1(:, 1)', 'O1', 250, 'positive');
    [pks_fi_p1_oz, locs_fi_p1_oz] = eegFindPeak(erps.face_inv,...
        windowsP1(:, 2)', 'Oz', 250, 'positive');        
    [pks_fi_p1_o2, locs_fi_p1_o2] = eegFindPeak(erps.face_inv,...
        windowsP1(:, 3)', 'O2', 250, 'positive');    
    
    % store - P1 | inverted
    erps.face_inv = eegStorePeak(erps.face_inv, 'P1', 'P7',...
        pks_fi_p1_p7, locs_fi_p1_p7);
    erps.face_inv = eegStorePeak(erps.face_inv, 'P1', 'Pz',...
        pks_fi_p1_pz, locs_fi_p1_pz);
    erps.face_inv = eegStorePeak(erps.face_inv, 'P1', 'P8',...
        pks_fi_p1_p8, locs_fi_p1_p8);
    erps.face_inv = eegStorePeak(erps.face_inv, 'P1', 'O1',...
        pks_fi_p1_o1, locs_fi_p1_o1);
    erps.face_inv = eegStorePeak(erps.face_inv, 'P1', 'Oz',...
        pks_fi_p1_oz, locs_fi_p1_oz);
    erps.face_inv = eegStorePeak(erps.face_inv, 'P1', 'O2',...
        pks_fi_p1_o2, locs_fi_p1_o2);    
    
    % find - N1 | upright
    [pks_fu_n1_p7, locs_fu_n1_p7] = eegFindPeak(erps.face_up,...
        windowsN1(:, 1)', 'P7', 250, 'negative');
    [pks_fu_n1_pz, locs_fu_n1_pz] = eegFindPeak(erps.face_up,...
        windowsN1(:, 2)', 'Pz', 250, 'negative');        
    [pks_fu_n1_p8, locs_fu_n1_p8] = eegFindPeak(erps.face_up,...
        windowsN1(:, 3)', 'P8', 250, 'negative');    

    % store N1 | upright
    erps.face_up = eegStorePeak(erps.face_up, 'N170', 'P7',...
        pks_fu_n1_p7, locs_fu_n1_p7);
    erps.face_up = eegStorePeak(erps.face_up, 'N170', 'Pz',...
        pks_fu_n1_pz, locs_fu_n1_pz);
    erps.face_up = eegStorePeak(erps.face_up, 'N170', 'P8',...
        pks_fu_n1_p8, locs_fu_n1_p8);
    
    % find - N1 | inverted
    [pks_fi_n1_p7, locs_fi_n1_p7] = eegFindPeak(erps.face_inv,...
        windowsN1(:, 1)', 'P7', 250, 'negative');
    [pks_fi_n1_pz, locs_fi_n1_pz] = eegFindPeak(erps.face_inv,...
        windowsN1(:, 2)', 'Pz', 250, 'negative');        
    [pks_fi_n1_p8, locs_fi_n1_p8] = eegFindPeak(erps.face_inv,...
        windowsN1(:, 3)', 'P8', 250, 'negative');    

    % store N1 | inverted
    erps.face_inv = eegStorePeak(erps.face_inv, 'N170', 'P7',...
        pks_fi_n1_p7, locs_fi_n1_p7);
    erps.face_inv = eegStorePeak(erps.face_inv, 'N170', 'Pz',...
        pks_fi_n1_pz, locs_fi_n1_pz);
    erps.face_inv = eegStorePeak(erps.face_inv, 'N170', 'P8',...
        pks_fi_n1_p8, locs_fi_n1_p8); 

end